#!/usr/bin/env python3
"""Generate and verify the hash-locked Lens CI Python environment."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "scripts/tagger/requirements-ci.in"
DEFAULT_LOCK = ROOT / "scripts/tagger/requirements-ci.txt"
TARGET_IMAGE = (
    "python@sha256:1b48a1b13ec678be8d84974541cc007d4367aaf01f985231daad1a940106efc0"
)
TARGET_PYTHON = "3.12.11"
TARGET_PIP = "25.0.1"
TARGET_SYSTEM = "Linux"
TARGET_MACHINE = "x86_64"
PYPI_INDEX = "https://pypi.org/simple"
NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
VERSION = re.compile(r"[A-Za-z0-9][A-Za-z0-9.!+_-]*")
SHA256 = re.compile(r"[0-9a-f]{64}")


class LockError(ValueError):
    pass


@dataclass(frozen=True, order=True)
class Requirement:
    name: str
    version: str
    sha256: str = ""


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def read_direct(path: Path) -> tuple[list[Requirement], str]:
    raw = path.read_bytes()
    requirements: list[Requirement] = []
    for line_number, raw_line in enumerate(raw.decode("utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.count("==") != 1:
            raise LockError(f"{path}:{line_number}: requirement must use one exact == pin")
        raw_name, version = line.split("==")
        if not NAME.fullmatch(raw_name) or not VERSION.fullmatch(version):
            raise LockError(f"{path}:{line_number}: unsupported requirement syntax")
        requirements.append(Requirement(canonical_name(raw_name), version))

    if not requirements:
        raise LockError(f"{path}: no direct requirements")
    names = [requirement.name for requirement in requirements]
    if len(names) != len(set(names)):
        raise LockError(f"{path}: duplicate normalized package name")
    if names != sorted(names):
        raise LockError(f"{path}: direct requirements must be sorted by normalized name")
    return requirements, hashlib.sha256(raw).hexdigest()


def header(input_sha256: str) -> list[str]:
    return [
        "# Generated by scripts/tagger/python_lock.py; do not edit by hand.",
        "# Regenerate only in the pinned target image named below.",
        f"# target-image: {TARGET_IMAGE}",
        f"# target-python: CPython {TARGET_PYTHON}",
        f"# target-pip: {TARGET_PIP}",
        f"# target-platform: {TARGET_SYSTEM} {TARGET_MACHINE}",
        f"# input-sha256: {input_sha256}",
    ]


def validate_report(
    report: object, direct: list[Requirement]
) -> list[Requirement]:
    if not isinstance(report, dict) or report.get("version") != "1":
        raise LockError("pip report must use schema version 1")
    if report.get("pip_version") != TARGET_PIP:
        raise LockError(f"pip report was not produced by pip {TARGET_PIP}")
    environment = report.get("environment")
    expected_environment = {
        "implementation_name": "cpython",
        "implementation_version": TARGET_PYTHON,
        "platform_machine": TARGET_MACHINE,
        "platform_system": TARGET_SYSTEM,
        "python_full_version": TARGET_PYTHON,
        "platform_python_implementation": "CPython",
        "python_version": "3.12",
        "sys_platform": "linux",
    }
    if not isinstance(environment, dict):
        raise LockError("pip report has no target environment")
    for key, expected in expected_environment.items():
        if environment.get(key) != expected:
            raise LockError(f"pip report target {key} is not {expected!r}")

    installs = report.get("install")
    if not isinstance(installs, list) or not installs:
        raise LockError("pip report contains no install plan")
    resolved: list[Requirement] = []
    requested: dict[str, str] = {}
    seen: set[str] = set()
    for index, entry in enumerate(installs):
        if not isinstance(entry, dict):
            raise LockError(f"pip report install entry {index} is not an object")
        if entry.get("is_yanked") is not False:
            raise LockError(f"pip report install entry {index} is yanked or lacks yanked status")
        metadata = entry.get("metadata")
        if not isinstance(metadata, dict):
            raise LockError(f"pip report install entry {index} has no metadata")
        raw_name = metadata.get("name")
        version = metadata.get("version")
        if not isinstance(raw_name, str) or not NAME.fullmatch(raw_name):
            raise LockError(f"pip report install entry {index} has an invalid name")
        if not isinstance(version, str) or not VERSION.fullmatch(version):
            raise LockError(f"pip report install entry {index} has an invalid version")
        name = canonical_name(raw_name)
        if name in seen:
            raise LockError(f"pip report resolves {name} more than once")
        seen.add(name)

        download = entry.get("download_info")
        if not isinstance(download, dict):
            raise LockError(f"pip report entry {name} has no download information")
        url = download.get("url")
        if not isinstance(url, str):
            raise LockError(f"pip report entry {name} has no artifact URL")
        parsed = urlsplit(url)
        if (
            parsed.scheme != "https"
            or parsed.hostname != "files.pythonhosted.org"
            or parsed.username is not None
            or parsed.password is not None
            or parsed.port is not None
            or parsed.query
            or parsed.fragment
            or not parsed.path.endswith(".whl")
        ):
            raise LockError(f"pip report entry {name} is not a PyPI HTTPS wheel")
        archive = download.get("archive_info")
        hashes = archive.get("hashes") if isinstance(archive, dict) else None
        digest = hashes.get("sha256") if isinstance(hashes, dict) else None
        if not isinstance(digest, str) or not SHA256.fullmatch(digest):
            raise LockError(f"pip report entry {name} lacks one lowercase SHA-256")
        if archive.get("hash") != f"sha256={digest}":
            raise LockError(f"pip report entry {name} has inconsistent artifact hashes")

        resolved.append(Requirement(name, version, digest))
        if entry.get("requested") is True:
            requested[name] = version
        elif entry.get("requested") is not False:
            raise LockError(f"pip report entry {name} lacks requested status")

    expected_requested = {item.name: item.version for item in direct}
    if requested != expected_requested:
        raise LockError(
            "pip report direct requests differ from requirements-ci.in: "
            f"expected {expected_requested}, got {requested}"
        )
    return sorted(resolved)


def render(requirements: list[Requirement], input_sha256: str) -> str:
    lines = header(input_sha256) + [""]
    for requirement in requirements:
        lines.extend(
            [
                f"{requirement.name}=={requirement.version} \\",
                f"    --hash=sha256:{requirement.sha256}",
            ]
        )
    return "\n".join(lines) + "\n"


def parse_lock(path: Path, input_sha256: str) -> list[Requirement]:
    lines = path.read_text(encoding="utf-8").splitlines()
    expected_header = header(input_sha256)
    if lines[: len(expected_header)] != expected_header:
        raise LockError(f"{path}: generated header or input digest is stale")
    body = lines[len(expected_header) :]
    if not body or body.pop(0) != "":
        raise LockError(f"{path}: generated header must be followed by one blank line")
    if not body or len(body) % 2:
        raise LockError(f"{path}: lock entries must be exact pin/hash pairs")

    requirements: list[Requirement] = []
    pin_pattern = re.compile(r"([a-z0-9][a-z0-9-]*)==([A-Za-z0-9][A-Za-z0-9.!+_-]*) \\")
    hash_pattern = re.compile(r"    --hash=sha256:([0-9a-f]{64})")
    for index in range(0, len(body), 2):
        pin = pin_pattern.fullmatch(body[index])
        artifact_hash = hash_pattern.fullmatch(body[index + 1])
        if pin is None or artifact_hash is None:
            raise LockError(f"{path}: malformed lock entry near line {len(expected_header) + index + 2}")
        requirements.append(Requirement(pin.group(1), pin.group(2), artifact_hash.group(1)))

    if requirements != sorted(requirements):
        raise LockError(f"{path}: lock entries must be sorted and unique")
    names = [requirement.name for requirement in requirements]
    if len(names) != len(set(names)):
        raise LockError(f"{path}: duplicate package in lock")
    return requirements


def check(input_path: Path, lock_path: Path) -> None:
    direct, input_sha256 = read_direct(input_path)
    locked = parse_lock(lock_path, input_sha256)
    by_name = {requirement.name: requirement.version for requirement in locked}
    for requirement in direct:
        if by_name.get(requirement.name) != requirement.version:
            raise LockError(
                f"{lock_path}: direct pin {requirement.name}=={requirement.version} is absent"
            )


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def render_report(input_path: Path, report_path: Path, output_path: Path) -> None:
    direct, input_sha256 = read_direct(input_path)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    write_atomic(output_path, render(validate_report(report, direct), input_sha256))


def update(input_path: Path, output_path: Path) -> None:
    if f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}" != TARGET_PYTHON:
        raise LockError(f"lock updates require CPython {TARGET_PYTHON}")
    if importlib.metadata.version("pip") != TARGET_PIP:
        raise LockError(f"lock updates require pip {TARGET_PIP}")
    with tempfile.TemporaryDirectory(prefix="skwd-lens-python-lock-") as temporary:
        report_path = Path(temporary) / "report.json"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "--isolated",
                "install",
                "--disable-pip-version-check",
                "--dry-run",
                "--ignore-installed",
                "--only-binary=:all:",
                "--index-url",
                PYPI_INDEX,
                "--report",
                str(report_path),
                "--requirement",
                str(input_path),
            ],
            check=True,
        )
        render_report(input_path, report_path, output_path)


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    subparsers = result.add_subparsers(dest="command", required=True)
    for command in ("check", "update"):
        subparser = subparsers.add_parser(command)
        subparser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
        subparser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    render_parser = subparsers.add_parser("render-report", help=argparse.SUPPRESS)
    render_parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    render_parser.add_argument("--report", type=Path, required=True)
    render_parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    return result


def main() -> int:
    arguments = parser().parse_args()
    try:
        if arguments.command == "check":
            check(arguments.input, arguments.lock)
        elif arguments.command == "update":
            update(arguments.input, arguments.lock)
        else:
            render_report(arguments.input, arguments.report, arguments.lock)
    except (LockError, OSError, json.JSONDecodeError) as error:
        print(f"python lock: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
